/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Holiday = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Int,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SalaryCalculation = IDL.Record({
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'netSalary' : IDL.Nat,
  'employeeId' : IDL.Text,
  'daysPresent' : IDL.Nat,
  'workingDays' : IDL.Nat,
  'paidLeaveDays' : IDL.Nat,
  'baseSalary' : IDL.Nat,
});
export const Employee = IDL.Record({
  'id' : IDL.Text,
  'employeeCode' : IDL.Text,
  'joinDate' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'department' : IDL.Text,
  'position' : IDL.Text,
  'baseSalary' : IDL.Nat,
});
export const Attendance = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'halfdDay' : IDL.Null,
    'present' : IDL.Null,
    'late' : IDL.Null,
    'absent' : IDL.Null,
  }),
  'date' : IDL.Int,
  'photoUrl' : IDL.Text,
  'checkInTime' : IDL.Nat,
  'employeeId' : IDL.Text,
  'notes' : IDL.Text,
  'checkOutTime' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'employeeId' : IDL.Opt(IDL.Text),
});
export const Leave = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'endDate' : IDL.Int,
  'approvedBy' : IDL.Text,
  'employeeId' : IDL.Text,
  'leaveType' : IDL.Variant({
    'sick' : IDL.Null,
    'annual' : IDL.Null,
    'unpaid' : IDL.Null,
    'casual' : IDL.Null,
  }),
  'startDate' : IDL.Int,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHoliday' : IDL.Func([Holiday], [], []),
  'approveLeave' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateMonthlySalary' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [SalaryCalculation],
      ['query'],
    ),
  'createEmployee' : IDL.Func([Employee], [], []),
  'deactivateEmployee' : IDL.Func([IDL.Text], [], []),
  'getAttendanceByDate' : IDL.Func([IDL.Int], [IDL.Vec(Attendance)], ['query']),
  'getAttendanceByEmployee' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
  'getLeavesByEmployee' : IDL.Func([IDL.Text], [IDL.Vec(Leave)], ['query']),
  'getPendingLeaves' : IDL.Func([], [IDL.Vec(Leave)], ['query']),
  'getTodaySummary' : IDL.Func([IDL.Int], [IDL.Vec(Attendance)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'listHolidays' : IDL.Func([], [IDL.Vec(Holiday)], ['query']),
  'markAttendance' : IDL.Func([Attendance], [], []),
  'rejectLeave' : IDL.Func([IDL.Text], [], []),
  'removeHoliday' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitLeave' : IDL.Func([Leave], [], []),
  'updateCheckOut' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateEmployee' : IDL.Func([IDL.Text, Employee], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Holiday = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Int,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SalaryCalculation = IDL.Record({
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'netSalary' : IDL.Nat,
    'employeeId' : IDL.Text,
    'daysPresent' : IDL.Nat,
    'workingDays' : IDL.Nat,
    'paidLeaveDays' : IDL.Nat,
    'baseSalary' : IDL.Nat,
  });
  const Employee = IDL.Record({
    'id' : IDL.Text,
    'employeeCode' : IDL.Text,
    'joinDate' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'department' : IDL.Text,
    'position' : IDL.Text,
    'baseSalary' : IDL.Nat,
  });
  const Attendance = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'halfdDay' : IDL.Null,
      'present' : IDL.Null,
      'late' : IDL.Null,
      'absent' : IDL.Null,
    }),
    'date' : IDL.Int,
    'photoUrl' : IDL.Text,
    'checkInTime' : IDL.Nat,
    'employeeId' : IDL.Text,
    'notes' : IDL.Text,
    'checkOutTime' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'employeeId' : IDL.Opt(IDL.Text),
  });
  const Leave = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'endDate' : IDL.Int,
    'approvedBy' : IDL.Text,
    'employeeId' : IDL.Text,
    'leaveType' : IDL.Variant({
      'sick' : IDL.Null,
      'annual' : IDL.Null,
      'unpaid' : IDL.Null,
      'casual' : IDL.Null,
    }),
    'startDate' : IDL.Int,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHoliday' : IDL.Func([Holiday], [], []),
    'approveLeave' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateMonthlySalary' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [SalaryCalculation],
        ['query'],
      ),
    'createEmployee' : IDL.Func([Employee], [], []),
    'deactivateEmployee' : IDL.Func([IDL.Text], [], []),
    'getAttendanceByDate' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getAttendanceByEmployee' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
    'getLeavesByEmployee' : IDL.Func([IDL.Text], [IDL.Vec(Leave)], ['query']),
    'getPendingLeaves' : IDL.Func([], [IDL.Vec(Leave)], ['query']),
    'getTodaySummary' : IDL.Func([IDL.Int], [IDL.Vec(Attendance)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'listHolidays' : IDL.Func([], [IDL.Vec(Holiday)], ['query']),
    'markAttendance' : IDL.Func([Attendance], [], []),
    'rejectLeave' : IDL.Func([IDL.Text], [], []),
    'removeHoliday' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitLeave' : IDL.Func([Leave], [], []),
    'updateCheckOut' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateEmployee' : IDL.Func([IDL.Text, Employee], [], []),
  });
};

export const init = ({ IDL }) => { return []; };