/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance {
  'id' : string,
  'status' : { 'halfdDay' : null } |
    { 'present' : null } |
    { 'late' : null } |
    { 'absent' : null },
  'date' : bigint,
  'photoUrl' : string,
  'checkInTime' : bigint,
  'employeeId' : string,
  'notes' : string,
  'checkOutTime' : [] | [bigint],
}
export interface Employee {
  'id' : string,
  'employeeCode' : string,
  'joinDate' : string,
  'name' : string,
  'isActive' : boolean,
  'department' : string,
  'position' : string,
  'baseSalary' : bigint,
}
export interface Holiday {
  'id' : string,
  'date' : bigint,
  'name' : string,
  'description' : string,
}
export interface Leave {
  'id' : string,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'endDate' : bigint,
  'approvedBy' : string,
  'employeeId' : string,
  'leaveType' : { 'sick' : null } |
    { 'annual' : null } |
    { 'unpaid' : null } |
    { 'casual' : null },
  'startDate' : bigint,
  'reason' : string,
}
export interface SalaryCalculation {
  'month' : bigint,
  'year' : bigint,
  'netSalary' : bigint,
  'employeeId' : string,
  'daysPresent' : bigint,
  'workingDays' : bigint,
  'paidLeaveDays' : bigint,
  'baseSalary' : bigint,
}
export interface UserProfile { 'name' : string, 'employeeId' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addHoliday' : ActorMethod<[Holiday], undefined>,
  'approveLeave' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateMonthlySalary' : ActorMethod<
    [string, bigint, bigint],
    SalaryCalculation
  >,
  'createEmployee' : ActorMethod<[Employee], undefined>,
  'deactivateEmployee' : ActorMethod<[string], undefined>,
  'getAttendanceByDate' : ActorMethod<[bigint], Array<Attendance>>,
  'getAttendanceByEmployee' : ActorMethod<
    [string, bigint, bigint],
    Array<Attendance>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmployee' : ActorMethod<[string], [] | [Employee]>,
  'getLeavesByEmployee' : ActorMethod<[string], Array<Leave>>,
  'getPendingLeaves' : ActorMethod<[], Array<Leave>>,
  'getTodaySummary' : ActorMethod<[bigint], Array<Attendance>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listEmployees' : ActorMethod<[], Array<Employee>>,
  'listHolidays' : ActorMethod<[], Array<Holiday>>,
  'markAttendance' : ActorMethod<[Attendance], undefined>,
  'rejectLeave' : ActorMethod<[string], undefined>,
  'removeHoliday' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitLeave' : ActorMethod<[Leave], undefined>,
  'updateCheckOut' : ActorMethod<[string, bigint], undefined>,
  'updateEmployee' : ActorMethod<[string, Employee], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];